#include <stdio.h>
#include "Std_Types.h"
#include "BIT_math.h"
#include "ATmega32_Registers2.h"

#include "Port_int.h"
#include "Port_cfg.h"
#include "Port_priv.h"



void Port_vidInit(void)
{
#if PORT_u8PIN_0_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_0_DEFAULT_VALUE
#undef PORT_u8PIN_0_DEFAULT_DIR
#define PORT_u8PIN_0_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_0_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_0_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_0_DEFAULT_VALUE
#undef PORT_u8PIN_0_DEFAULT_DIR
#define PORT_u8PIN_0_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_0_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_0_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_0_DEFAULT_VALUE
#undef PORT_u8PIN_0_DEFAULT_DIR
#define PORT_u8PIN_0_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_0_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_0_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_0_DEFAULT_VALUE
#undef PORT_u8PIN_0_DEFAULT_DIR
#define PORT_u8PIN_0_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_0_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 0, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_1_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_1_DEFAULT_VALUE
#undef PORT_u8PIN_1_DEFAULT_DIR
#define PORT_u8PIN_1_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_1_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_1_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_1_DEFAULT_VALUE
#undef PORT_u8PIN_1_DEFAULT_DIR
#define PORT_u8PIN_1_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_1_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_1_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_1_DEFAULT_VALUE
#undef PORT_u8PIN_1_DEFAULT_DIR
#define PORT_u8PIN_1_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_1_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_1_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_1_DEFAULT_VALUE
#undef PORT_u8PIN_1_DEFAULT_DIR
#define PORT_u8PIN_1_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_1_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 1, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_2_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_2_DEFAULT_VALUE
#undef PORT_u8PIN_2_DEFAULT_DIR
#define PORT_u8PIN_2_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_2_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_2_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_2_DEFAULT_VALUE
#undef PORT_u8PIN_2_DEFAULT_DIR
#define PORT_u8PIN_2_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_2_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_2_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_2_DEFAULT_VALUE
#undef PORT_u8PIN_2_DEFAULT_DIR
#define PORT_u8PIN_2_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_2_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_2_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_2_DEFAULT_VALUE
#undef PORT_u8PIN_2_DEFAULT_DIR
#define PORT_u8PIN_2_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_2_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 2, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_3_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_3_DEFAULT_VALUE
#undef PORT_u8PIN_3_DEFAULT_DIR
#define PORT_u8PIN_3_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_3_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_3_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_3_DEFAULT_VALUE
#undef PORT_u8PIN_3_DEFAULT_DIR
#define PORT_u8PIN_3_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_3_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_3_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_3_DEFAULT_VALUE
#undef PORT_u8PIN_3_DEFAULT_DIR
#define PORT_u8PIN_3_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_3_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_3_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_3_DEFAULT_VALUE
#undef PORT_u8PIN_3_DEFAULT_DIR
#define PORT_u8PIN_3_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_3_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 3, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_4_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_4_DEFAULT_VALUE
#undef PORT_u8PIN_4_DEFAULT_DIR
#define PORT_u8PIN_4_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_4_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_4_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_4_DEFAULT_VALUE
#undef PORT_u8PIN_4_DEFAULT_DIR
#define PORT_u8PIN_4_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_4_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_4_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_4_DEFAULT_VALUE
#undef PORT_u8PIN_4_DEFAULT_DIR
#define PORT_u8PIN_4_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_4_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_4_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_4_DEFAULT_VALUE
#undef PORT_u8PIN_4_DEFAULT_DIR
#define PORT_u8PIN_4_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_4_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 4, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_5_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_5_DEFAULT_VALUE
#undef PORT_u8PIN_5_DEFAULT_DIR
#define PORT_u8PIN_5_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_5_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_5_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_5_DEFAULT_VALUE
#undef PORT_u8PIN_5_DEFAULT_DIR
#define PORT_u8PIN_5_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_5_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_5_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_5_DEFAULT_VALUE
#undef PORT_u8PIN_5_DEFAULT_DIR
#define PORT_u8PIN_5_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_5_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_5_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_5_DEFAULT_VALUE
#undef PORT_u8PIN_5_DEFAULT_DIR
#define PORT_u8PIN_5_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_5_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 5, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_6_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_6_DEFAULT_VALUE
#undef PORT_u8PIN_6_DEFAULT_DIR
#define PORT_u8PIN_6_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_6_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_6_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_6_DEFAULT_VALUE
#undef PORT_u8PIN_6_DEFAULT_DIR
#define PORT_u8PIN_6_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_6_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_6_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_6_DEFAULT_VALUE
#undef PORT_u8PIN_6_DEFAULT_DIR
#define PORT_u8PIN_6_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_6_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_6_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_6_DEFAULT_VALUE
#undef PORT_u8PIN_6_DEFAULT_DIR
#define PORT_u8PIN_6_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_6_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 6, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_7_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_7_DEFAULT_VALUE
#undef PORT_u8PIN_7_DEFAULT_DIR
#define PORT_u8PIN_7_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_7_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_7_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_7_DEFAULT_VALUE
#undef PORT_u8PIN_7_DEFAULT_DIR
#define PORT_u8PIN_7_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_7_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_7_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_7_DEFAULT_VALUE
#undef PORT_u8PIN_7_DEFAULT_DIR
#define PORT_u8PIN_7_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_7_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_7_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_7_DEFAULT_VALUE
#undef PORT_u8PIN_7_DEFAULT_DIR
#define PORT_u8PIN_7_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_7_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 7, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_8_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_8_DEFAULT_VALUE
#undef PORT_u8PIN_8_DEFAULT_DIR
#define PORT_u8PIN_8_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_8_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_8_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_8_DEFAULT_VALUE
#undef PORT_u8PIN_8_DEFAULT_DIR
#define PORT_u8PIN_8_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_8_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_8_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_8_DEFAULT_VALUE
#undef PORT_u8PIN_8_DEFAULT_DIR
#define PORT_u8PIN_8_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_8_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_8_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_8_DEFAULT_VALUE
#undef PORT_u8PIN_8_DEFAULT_DIR
#define PORT_u8PIN_8_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_8_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 8, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_9_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_9_DEFAULT_VALUE
#undef PORT_u8PIN_9_DEFAULT_DIR
#define PORT_u8PIN_9_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_9_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_9_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_9_DEFAULT_VALUE
#undef PORT_u8PIN_9_DEFAULT_DIR
#define PORT_u8PIN_9_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_9_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_9_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_9_DEFAULT_VALUE
#undef PORT_u8PIN_9_DEFAULT_DIR
#define PORT_u8PIN_9_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_9_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_9_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_9_DEFAULT_VALUE
#undef PORT_u8PIN_9_DEFAULT_DIR
#define PORT_u8PIN_9_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_9_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 9, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_10_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_10_DEFAULT_VALUE
#undef PORT_u8PIN_10_DEFAULT_DIR
#define PORT_u8PIN_10_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_10_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_10_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_10_DEFAULT_VALUE
#undef PORT_u8PIN_10_DEFAULT_DIR
#define PORT_u8PIN_10_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_10_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_10_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_10_DEFAULT_VALUE
#undef PORT_u8PIN_10_DEFAULT_DIR
#define PORT_u8PIN_10_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_10_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_10_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_10_DEFAULT_VALUE
#undef PORT_u8PIN_10_DEFAULT_DIR
#define PORT_u8PIN_10_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_10_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 10, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_11_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_11_DEFAULT_VALUE
#undef PORT_u8PIN_11_DEFAULT_DIR
#define PORT_u8PIN_11_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_11_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_11_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_11_DEFAULT_VALUE
#undef PORT_u8PIN_11_DEFAULT_DIR
#define PORT_u8PIN_11_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_11_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_11_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_11_DEFAULT_VALUE
#undef PORT_u8PIN_11_DEFAULT_DIR
#define PORT_u8PIN_11_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_11_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_11_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_11_DEFAULT_VALUE
#undef PORT_u8PIN_11_DEFAULT_DIR
#define PORT_u8PIN_11_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_11_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 11, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_12_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_12_DEFAULT_VALUE
#undef PORT_u8PIN_12_DEFAULT_DIR
#define PORT_u8PIN_12_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_12_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_12_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_12_DEFAULT_VALUE
#undef PORT_u8PIN_12_DEFAULT_DIR
#define PORT_u8PIN_12_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_12_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_12_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_12_DEFAULT_VALUE
#undef PORT_u8PIN_12_DEFAULT_DIR
#define PORT_u8PIN_12_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_12_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_12_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_12_DEFAULT_VALUE
#undef PORT_u8PIN_12_DEFAULT_DIR
#define PORT_u8PIN_12_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_12_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 12, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_13_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_13_DEFAULT_VALUE
#undef PORT_u8PIN_13_DEFAULT_DIR
#define PORT_u8PIN_13_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_13_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_13_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_13_DEFAULT_VALUE
#undef PORT_u8PIN_13_DEFAULT_DIR
#define PORT_u8PIN_13_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_13_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_13_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_13_DEFAULT_VALUE
#undef PORT_u8PIN_13_DEFAULT_DIR
#define PORT_u8PIN_13_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_13_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_13_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_13_DEFAULT_VALUE
#undef PORT_u8PIN_13_DEFAULT_DIR
#define PORT_u8PIN_13_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_13_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 13, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_14_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_14_DEFAULT_VALUE
#undef PORT_u8PIN_14_DEFAULT_DIR
#define PORT_u8PIN_14_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_14_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_14_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_14_DEFAULT_VALUE
#undef PORT_u8PIN_14_DEFAULT_DIR
#define PORT_u8PIN_14_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_14_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_14_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_14_DEFAULT_VALUE
#undef PORT_u8PIN_14_DEFAULT_DIR
#define PORT_u8PIN_14_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_14_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_14_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_14_DEFAULT_VALUE
#undef PORT_u8PIN_14_DEFAULT_DIR
#define PORT_u8PIN_14_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_14_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 14, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_15_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_15_DEFAULT_VALUE
#undef PORT_u8PIN_15_DEFAULT_DIR
#define PORT_u8PIN_15_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_15_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_15_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_15_DEFAULT_VALUE
#undef PORT_u8PIN_15_DEFAULT_DIR
#define PORT_u8PIN_15_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_15_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_15_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_15_DEFAULT_VALUE
#undef PORT_u8PIN_15_DEFAULT_DIR
#define PORT_u8PIN_15_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_15_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_15_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_15_DEFAULT_VALUE
#undef PORT_u8PIN_15_DEFAULT_DIR
#define PORT_u8PIN_15_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_15_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 15, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_16_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_16_DEFAULT_VALUE
#undef PORT_u8PIN_16_DEFAULT_DIR
#define PORT_u8PIN_16_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_16_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_16_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_16_DEFAULT_VALUE
#undef PORT_u8PIN_16_DEFAULT_DIR
#define PORT_u8PIN_16_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_16_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_16_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_16_DEFAULT_VALUE
#undef PORT_u8PIN_16_DEFAULT_DIR
#define PORT_u8PIN_16_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_16_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_16_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_16_DEFAULT_VALUE
#undef PORT_u8PIN_16_DEFAULT_DIR
#define PORT_u8PIN_16_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_16_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 16, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_17_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_17_DEFAULT_VALUE
#undef PORT_u8PIN_17_DEFAULT_DIR
#define PORT_u8PIN_17_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_17_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_17_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_17_DEFAULT_VALUE
#undef PORT_u8PIN_17_DEFAULT_DIR
#define PORT_u8PIN_17_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_17_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_17_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_17_DEFAULT_VALUE
#undef PORT_u8PIN_17_DEFAULT_DIR
#define PORT_u8PIN_17_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_17_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_17_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_17_DEFAULT_VALUE
#undef PORT_u8PIN_17_DEFAULT_DIR
#define PORT_u8PIN_17_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_17_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 17, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_18_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_18_DEFAULT_VALUE
#undef PORT_u8PIN_18_DEFAULT_DIR
#define PORT_u8PIN_18_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_18_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_18_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_18_DEFAULT_VALUE
#undef PORT_u8PIN_18_DEFAULT_DIR
#define PORT_u8PIN_18_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_18_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_18_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_18_DEFAULT_VALUE
#undef PORT_u8PIN_18_DEFAULT_DIR
#define PORT_u8PIN_18_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_18_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_18_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_18_DEFAULT_VALUE
#undef PORT_u8PIN_18_DEFAULT_DIR
#define PORT_u8PIN_18_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_18_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 18, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_19_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_19_DEFAULT_VALUE
#undef PORT_u8PIN_19_DEFAULT_DIR
#define PORT_u8PIN_19_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_19_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_19_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_19_DEFAULT_VALUE
#undef PORT_u8PIN_19_DEFAULT_DIR
#define PORT_u8PIN_19_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_19_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_19_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_19_DEFAULT_VALUE
#undef PORT_u8PIN_19_DEFAULT_DIR
#define PORT_u8PIN_19_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_19_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_19_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_19_DEFAULT_VALUE
#undef PORT_u8PIN_19_DEFAULT_DIR
#define PORT_u8PIN_19_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_19_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 19, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_20_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_20_DEFAULT_VALUE
#undef PORT_u8PIN_20_DEFAULT_DIR
#define PORT_u8PIN_20_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_20_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_20_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_20_DEFAULT_VALUE
#undef PORT_u8PIN_20_DEFAULT_DIR
#define PORT_u8PIN_20_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_20_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_20_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_20_DEFAULT_VALUE
#undef PORT_u8PIN_20_DEFAULT_DIR
#define PORT_u8PIN_20_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_20_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_20_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_20_DEFAULT_VALUE
#undef PORT_u8PIN_20_DEFAULT_DIR
#define PORT_u8PIN_20_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_20_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 20, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_21_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_21_DEFAULT_VALUE
#undef PORT_u8PIN_21_DEFAULT_DIR
#define PORT_u8PIN_21_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_21_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_21_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_21_DEFAULT_VALUE
#undef PORT_u8PIN_21_DEFAULT_DIR
#define PORT_u8PIN_21_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_21_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_21_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_21_DEFAULT_VALUE
#undef PORT_u8PIN_21_DEFAULT_DIR
#define PORT_u8PIN_21_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_21_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_21_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_21_DEFAULT_VALUE
#undef PORT_u8PIN_21_DEFAULT_DIR
#define PORT_u8PIN_21_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_21_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 21, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_22_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_22_DEFAULT_VALUE
#undef PORT_u8PIN_22_DEFAULT_DIR
#define PORT_u8PIN_22_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_22_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_22_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_22_DEFAULT_VALUE
#undef PORT_u8PIN_22_DEFAULT_DIR
#define PORT_u8PIN_22_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_22_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_22_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_22_DEFAULT_VALUE
#undef PORT_u8PIN_22_DEFAULT_DIR
#define PORT_u8PIN_22_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_22_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_22_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_22_DEFAULT_VALUE
#undef PORT_u8PIN_22_DEFAULT_DIR
#define PORT_u8PIN_22_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_22_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 22, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_23_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_23_DEFAULT_VALUE
#undef PORT_u8PIN_23_DEFAULT_DIR
#define PORT_u8PIN_23_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_23_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_23_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_23_DEFAULT_VALUE
#undef PORT_u8PIN_23_DEFAULT_DIR
#define PORT_u8PIN_23_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_23_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_23_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_23_DEFAULT_VALUE
#undef PORT_u8PIN_23_DEFAULT_DIR
#define PORT_u8PIN_23_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_23_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_23_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_23_DEFAULT_VALUE
#undef PORT_u8PIN_23_DEFAULT_DIR
#define PORT_u8PIN_23_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_23_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 23, the default mode has been set (output low)"

#endif

#if PORT_u8PIN_24_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_24_DEFAULT_VALUE
#undef PORT_u8PIN_24_DEFAULT_DIR
#define PORT_u8PIN_24_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_24_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_24_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_24_DEFAULT_VALUE
#undef PORT_u8PIN_24_DEFAULT_DIR
#define PORT_u8PIN_24_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_24_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_24_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_24_DEFAULT_VALUE
#undef PORT_u8PIN_24_DEFAULT_DIR
#define PORT_u8PIN_24_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_24_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_24_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_24_DEFAULT_VALUE
#undef PORT_u8PIN_24_DEFAULT_DIR
#define PORT_u8PIN_24_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_24_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 24, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_25_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_25_DEFAULT_VALUE
#undef PORT_u8PIN_25_DEFAULT_DIR
#define PORT_u8PIN_25_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_25_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_25_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_25_DEFAULT_VALUE
#undef PORT_u8PIN_25_DEFAULT_DIR
#define PORT_u8PIN_25_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_25_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_25_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_25_DEFAULT_VALUE
#undef PORT_u8PIN_25_DEFAULT_DIR
#define PORT_u8PIN_25_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_25_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_25_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_25_DEFAULT_VALUE
#undef PORT_u8PIN_25_DEFAULT_DIR
#define PORT_u8PIN_25_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_25_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 25, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_26_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_26_DEFAULT_VALUE
#undef PORT_u8PIN_26_DEFAULT_DIR
#define PORT_u8PIN_26_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_26_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_26_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_26_DEFAULT_VALUE
#undef PORT_u8PIN_26_DEFAULT_DIR
#define PORT_u8PIN_26_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_26_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_26_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_26_DEFAULT_VALUE
#undef PORT_u8PIN_26_DEFAULT_DIR
#define PORT_u8PIN_26_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_26_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_26_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_26_DEFAULT_VALUE
#undef PORT_u8PIN_26_DEFAULT_DIR
#define PORT_u8PIN_26_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_26_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 26, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_27_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_27_DEFAULT_VALUE
#undef PORT_u8PIN_27_DEFAULT_DIR
#define PORT_u8PIN_27_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_27_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_27_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_27_DEFAULT_VALUE
#undef PORT_u8PIN_27_DEFAULT_DIR
#define PORT_u8PIN_27_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_27_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_27_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_27_DEFAULT_VALUE
#undef PORT_u8PIN_27_DEFAULT_DIR
#define PORT_u8PIN_27_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_27_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_27_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_27_DEFAULT_VALUE
#undef PORT_u8PIN_27_DEFAULT_DIR
#define PORT_u8PIN_27_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_27_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 27, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_28_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_28_DEFAULT_VALUE
#undef PORT_u8PIN_28_DEFAULT_DIR
#define PORT_u8PIN_28_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_28_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_28_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_28_DEFAULT_VALUE
#undef PORT_u8PIN_28_DEFAULT_DIR
#define PORT_u8PIN_28_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_28_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_28_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_28_DEFAULT_VALUE
#undef PORT_u8PIN_28_DEFAULT_DIR
#define PORT_u8PIN_28_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_28_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_28_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_28_DEFAULT_VALUE
#undef PORT_u8PIN_28_DEFAULT_DIR
#define PORT_u8PIN_28_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_28_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 28, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_29_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_29_DEFAULT_VALUE
#undef PORT_u8PIN_29_DEFAULT_DIR
#define PORT_u8PIN_29_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_29_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_29_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_29_DEFAULT_VALUE
#undef PORT_u8PIN_29_DEFAULT_DIR
#define PORT_u8PIN_29_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_29_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_29_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_29_DEFAULT_VALUE
#undef PORT_u8PIN_29_DEFAULT_DIR
#define PORT_u8PIN_29_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_29_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_29_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_29_DEFAULT_VALUE
#undef PORT_u8PIN_29_DEFAULT_DIR
#define PORT_u8PIN_29_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_29_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 29, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_30_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_30_DEFAULT_VALUE
#undef PORT_u8PIN_30_DEFAULT_DIR
#define PORT_u8PIN_30_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_30_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_30_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_30_DEFAULT_VALUE
#undef PORT_u8PIN_30_DEFAULT_DIR
#define PORT_u8PIN_30_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_30_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_30_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_30_DEFAULT_VALUE
#undef PORT_u8PIN_30_DEFAULT_DIR
#define PORT_u8PIN_30_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_30_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_30_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_30_DEFAULT_VALUE
#undef PORT_u8PIN_30_DEFAULT_DIR
#define PORT_u8PIN_30_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_30_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 30, the default mode has been set (output low)"
#endif

#if PORT_u8PIN_31_INIT_MODE == PORT_u8OUTPUT_LOW_INIT
#undef PORT_u8PIN_31_DEFAULT_VALUE
#undef PORT_u8PIN_31_DEFAULT_DIR
#define PORT_u8PIN_31_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_31_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_31_INIT_MODE == PORT_u8OUTPUT_HIGH
#undef PORT_u8PIN_31_DEFAULT_VALUE
#undef PORT_u8PIN_31_DEFAULT_DIR
#define PORT_u8PIN_31_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_31_DEFAULT_DIR   PORT_u8OUTPUT
#elif PORT_u8PIN_31_INIT_MODE == PORT_u8INPUT_HIGH_IMP
#undef PORT_u8PIN_31_DEFAULT_VALUE
#undef PORT_u8PIN_31_DEFAULT_DIR
#define PORT_u8PIN_31_DEFAULT_VALUE PORT_u8LOW
#define PORT_u8PIN_31_DEFAULT_DIR   PORT_u8INPUT
#elif PORT_u8PIN_31_INIT_MODE == PORT_u8INPUT_PULL_UP
#undef PORT_u8PIN_31_DEFAULT_VALUE
#undef PORT_u8PIN_31_DEFAULT_DIR
#define PORT_u8PIN_31_DEFAULT_VALUE PORT_u8HIGH
#define PORT_u8PIN_31_DEFAULT_DIR   PORT_u8INPUT
#else
#warning "You have entered a wrong initial mode for pin 31, the default mode has been set (output low)"
#endif

	DDRA = (u8) CONC(PORT_u8PIN_7_DEFAULT_DIR,PORT_u8PIN_6_DEFAULT_DIR,PORT_u8PIN_5_DEFAULT_DIR,PORT_u8PIN_4_DEFAULT_DIR,PORT_u8PIN_3_DEFAULT_DIR,PORT_u8PIN_2_DEFAULT_DIR,PORT_u8PIN_1_DEFAULT_DIR,PORT_u8PIN_0_DEFAULT_DIR);
	DDRB = (u8) CONC(PORT_u8PIN_15_DEFAULT_DIR,PORT_u8PIN_14_DEFAULT_DIR,PORT_u8PIN_13_DEFAULT_DIR,PORT_u8PIN_12_DEFAULT_DIR,PORT_u8PIN_11_DEFAULT_DIR,PORT_u8PIN_10_DEFAULT_DIR,PORT_u8PIN_9_DEFAULT_DIR,PORT_u8PIN_8_DEFAULT_DIR);
	DDRC = (u8) CONC(PORT_u8PIN_23_DEFAULT_DIR,PORT_u8PIN_22_DEFAULT_DIR,PORT_u8PIN_21_DEFAULT_DIR,PORT_u8PIN_20_DEFAULT_DIR,PORT_u8PIN_19_DEFAULT_DIR,PORT_u8PIN_18_DEFAULT_DIR,PORT_u8PIN_17_DEFAULT_DIR,PORT_u8PIN_16_DEFAULT_DIR);
	DDRD = (u8) CONC(PORT_u8PIN_31_DEFAULT_DIR,PORT_u8PIN_30_DEFAULT_DIR,PORT_u8PIN_29_DEFAULT_DIR,PORT_u8PIN_28_DEFAULT_DIR,PORT_u8PIN_27_DEFAULT_DIR,PORT_u8PIN_26_DEFAULT_DIR,PORT_u8PIN_25_DEFAULT_DIR,PORT_u8PIN_24_DEFAULT_DIR);

	PORTA = (u8) CONC(PORT_u8PIN_7_DEFAULT_VALUE,PORT_u8PIN_6_DEFAULT_VALUE,PORT_u8PIN_5_DEFAULT_VALUE,PORT_u8PIN_4_DEFAULT_VALUE,PORT_u8PIN_3_DEFAULT_VALUE,PORT_u8PIN_2_DEFAULT_VALUE,PORT_u8PIN_1_DEFAULT_VALUE,PORT_u8PIN_0_DEFAULT_VALUE);
	PORTB = (u8) CONC(PORT_u8PIN_15_DEFAULT_VALUE,PORT_u8PIN_14_DEFAULT_VALUE,PORT_u8PIN_13_DEFAULT_VALUE,PORT_u8PIN_12_DEFAULT_VALUE,PORT_u8PIN_11_DEFAULT_VALUE,PORT_u8PIN_10_DEFAULT_VALUE,PORT_u8PIN_9_DEFAULT_VALUE,PORT_u8PIN_8_DEFAULT_VALUE);
	PORTC = (u8) CONC(PORT_u8PIN_23_DEFAULT_VALUE,PORT_u8PIN_22_DEFAULT_VALUE,PORT_u8PIN_21_DEFAULT_VALUE,PORT_u8PIN_20_DEFAULT_VALUE,PORT_u8PIN_19_DEFAULT_VALUE,PORT_u8PIN_18_DEFAULT_VALUE,PORT_u8PIN_17_DEFAULT_VALUE,PORT_u8PIN_16_DEFAULT_VALUE);
	PORTD = (u8) CONC(PORT_u8PIN_31_DEFAULT_VALUE,PORT_u8PIN_30_DEFAULT_VALUE,PORT_u8PIN_29_DEFAULT_VALUE,PORT_u8PIN_28_DEFAULT_VALUE,PORT_u8PIN_27_DEFAULT_VALUE,PORT_u8PIN_26_DEFAULT_VALUE,PORT_u8PIN_25_DEFAULT_VALUE,PORT_u8PIN_24_DEFAULT_VALUE);
}


ReturnStatus_e Port_vidSetPinMode(u8 Copy_u8SwPinNo, u8 Copy_u8SwPinMode)
{
	ReturnStatus_e returnValue = E_OK;

	u8 Loc_u8PortId;
	u8 Loc_u8PinId;

	Loc_u8PortId = (u8)Copy_u8SwPinNo / 8;
	Loc_u8PinId = (u8)Copy_u8SwPinNo % 8;

	switch(Loc_u8PortId)
	{
	/*Port A*/
	case 0:
		if(Copy_u8SwPinMode == PORT_u8OUTPUT_LOW)
		{
			SET_BIT(DDRA,Loc_u8PinId);
			CLR_BIT(PORTA,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8OUTPUT_HIGH)
		{
			SET_BIT(DDRA,Loc_u8PinId);
			SET_BIT(PORTA,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_HIGH_IMP)
		{
			CLR_BIT(DDRA,Loc_u8PinId);
			CLR_BIT(PORTA,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_PULL_UP)
		{
			CLR_BIT(DDRA,Loc_u8PinId);
			SET_BIT(PORTA,Loc_u8PinId);
		}
		break;
		/*Port B*/
	case 1:
		if(Copy_u8SwPinMode == PORT_u8OUTPUT_LOW)
		{
			SET_BIT(DDRB,Loc_u8PinId);
			CLR_BIT(PORTB,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8OUTPUT_HIGH)
		{
			SET_BIT(DDRB,Loc_u8PinId);
			SET_BIT(PORTB,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_HIGH_IMP)
		{
			CLR_BIT(DDRB,Loc_u8PinId);
			CLR_BIT(PORTB,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_PULL_UP)
		{
			CLR_BIT(DDRB,Loc_u8PinId);
			SET_BIT(PORTB,Loc_u8PinId);
		}
		break;
		/*Port C*/
	case 2:
		if(Copy_u8SwPinMode == PORT_u8OUTPUT_LOW)
		{
			SET_BIT(DDRC,Loc_u8PinId);
			CLR_BIT(PORTC,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8OUTPUT_HIGH)
		{
			SET_BIT(DDRC,Loc_u8PinId);
			SET_BIT(PORTC,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_HIGH_IMP)
		{
			CLR_BIT(DDRC,Loc_u8PinId);
			CLR_BIT(PORTC,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_PULL_UP)
		{
			CLR_BIT(DDRC,Loc_u8PinId);
			SET_BIT(PORTC,Loc_u8PinId);
		}
		break;
		/*Port D*/
	case 3:
		if(Copy_u8SwPinMode == PORT_u8OUTPUT_LOW)
		{
			SET_BIT(DDRD,Loc_u8PinId);
			CLR_BIT(PORTD,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8OUTPUT_HIGH)
		{
			SET_BIT(DDRD,Loc_u8PinId);
			SET_BIT(PORTD,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_HIGH_IMP)
		{
			CLR_BIT(DDRD,Loc_u8PinId);
			CLR_BIT(PORTD,Loc_u8PinId);
		}
		else if(Copy_u8SwPinMode == PORT_u8INPUT_PULL_UP)
		{
			CLR_BIT(DDRD,Loc_u8PinId);
			SET_BIT(PORTD,Loc_u8PinId);
		}
		break;
	default:
		returnValue = E_NOK;
		break;
	}

	return returnValue;
}

ReturnStatus_e Port_vidSetPinDir(u8 Copy_u8SwPinNo, u8 Copy_u8SwPinDir)
{
	ReturnStatus_e returnValue = E_OK;

	u8 Loc_u8PortId;
	u8 Loc_u8PinId;

	Loc_u8PortId = (u8)Copy_u8SwPinNo / 8;
	Loc_u8PinId = (u8)Copy_u8SwPinNo % 8;

	switch(Loc_u8PortId)
		{
		/*Port A*/
		case 0:
			if(Copy_u8SwPinDir == PORT_u8OUTPUT)
			{
				SET_BIT(DDRA,Loc_u8PinId);
			}
			else if(Copy_u8SwPinDir == PORT_u8INPUT)
			{
				CLR_BIT(DDRA,Loc_u8PinId);
			}
			break;
			/*Port B*/
		case 1:
			if(Copy_u8SwPinDir == PORT_u8OUTPUT)
			{
				SET_BIT(DDRB,Loc_u8PinId);
			}
			else if(Copy_u8SwPinDir == PORT_u8INPUT)
			{
				CLR_BIT(DDRB,Loc_u8PinId);
			}
			break;
			/*Port C*/
		case 2:
			if(Copy_u8SwPinDir == PORT_u8OUTPUT)
			{
				SET_BIT(DDRC,Loc_u8PinId);
			}
			else if(Copy_u8SwPinDir == PORT_u8INPUT)
			{
				CLR_BIT(DDRC,Loc_u8PinId);
			}
			break;
			/*Port D*/
		case 3:
			if(Copy_u8SwPinDir == PORT_u8OUTPUT)
			{
				SET_BIT(DDRD,Loc_u8PinId);
			}
			else if(Copy_u8SwPinDir == PORT_u8INPUT)
			{
				CLR_BIT(DDRD,Loc_u8PinId);
			}
			break;
		default:
			returnValue = E_NOK;
			break;
		}


	return returnValue;
}
